server:
  port: 8080

spring:
  kafka:
    bootstrap-servers:
      - 13.125.41.222:9092
      - 13.125.41.222:19092
      - 13.125.41.222 :29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        partitioner.class: org.apache.kafka.clients.producer.RoundRobinPartitioner

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userDB
    driver-class-name: org.h2.Driver
    username: sa
    password:



